<div class="sections nav-sections" style="height:46px !important;">
    <div class="section-items nav-sections-items" data-mage-init="{&quot;tabs&quot;:{&quot;openedState&quot;:&quot;active&quot;}}">

        <div class="section-item-content nav-sections-item-content" id="store.menu" data-role="content">


            <nav class="tiberis-navigation" role="navigation">
                <li class="tiberis-navigation-menu">
                    <a class="tiberis-navigation-title">КАТАЛОГ</a>
                    <ul>

                        <li class="tiberis-navigation-item level0">
                            <a href="http://51.254.132.135/" class="tiberis-navigation-item top"><span>Главная</span></a>
                        </li>

                        <li class="tiberis-navigation-item level0 parent ">
                            <a href="http://51.254.132.135/svarochnye-apparaty.html" class="tiberis-navigation-item top"><span>Сварочные аппараты</span></a>

                            <div class="tiberis-navigation-item submenu">
                                <div class="tiberis-navigation-item-row">
                                    <ul class="tiberis-navigation-item-subchildmenu">
                                        <li class="tiberis-navigation-item level1 ">
                                            <a href="http://51.254.132.135/svarochnye-apparaty/svarochnyj-invertor.html"><span>Сварочные инверторы</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>

                        <li class="tiberis-navigation-item level0">
                            <a href="http://51.254.132.135/svarochnye-materialy.html" class="tiberis-navigation-item top"><span>Сварочные материалы</span></a>
                        </li>

                    </ul>
                </li>
            </nav>

            <script type="text/javascript">

                require([
                    'jquery',
                    'Magento_Theme/js/tiberis-menu'
                ], function ($) {
                    tiberisMenu.init({
                        menuClass: "tiberis-navigation"
                    },$);
                });

            </script>

        </div>
    </div>
</div>