<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    $fields = array();
    $fields[0][0] = 'naprjazhenie';
    $fields[1][0] = 'svarochnyj_tok';
    $fields[2][0] = 'moschnost';
    $fields[3][0] = 'diametr_jelektroda_max';
    $fields[4][0] = 'ves';
    $fields[5][0] = 'strana_proizvoditelNOOOOO';
    $fields[6][0] = 'svarochnyj_tok_pri_pv_60';
    $fields[7][0] = 'svarochnyj_tok_pri_pv_100';
    $fields[8][0] = 'cifrovoj_displej';
    $fields[9][0] = 'pv_na_max_toke';
    $fields[10][0] = 'pn_ponizhennoe_naprjazhenie';
    $fields[11][0] = 'v_kejse';

    $fields[0][1] = 'Напряжение: ';
    $fields[1][1] = 'Сварочный ток: ';
    $fields[2][1] = 'Мощность: ';
    $fields[3][1] = 'Диаметр электрода MAX';
    $fields[4][1] = 'Вес: ';
    $fields[5][1] = 'Страна производитель: ';
    $fields[6][1] = 'Сварочный ток при ПВ 60: ';
    $fields[7][1] = 'Сварочный ток при ПВ 100: ';
    $fields[8][1] = 'Цифровой дисплей: ';
    $fields[9][1] = 'ПВ на MAX токе: ';
    $fields[10][1] = 'Пониженное напряжение: ';
    $fields[11][1] = 'В кейсе: ';

    $fields[0][2] = 'В';
    $fields[1][2] = 'А';
    $fields[2][2] = 'кВт';
    $fields[3][2] = 'мм';
    $fields[4][2] = 'кг';
    $fields[5][2] = '';
    $fields[6][2] = 'А';
    $fields[7][2] = 'А';
    $fields[8][2] = '';
    $fields[9][2] = 'А';
    $fields[10][2] = '';
    $fields[11][2] = '';

    $dots = '<text class="dots"></text>';

    $_className = 'atribelem';
    $_attributeType = $block->getAtType();
    $_attributeAddAttribute = $block->getAddAttribute();

    $i = 0;
    while ($i < count($fields)) {
        $t = ucfirst($fields[$i][0]);
        $_call = 'get'.$t;
        $_code = $fields[$i][0];
            $_attributeLabel = $fields[$i][1];
            if ($_attributeType && $_attributeType == 'text') {
                $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
            } else {
                $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
            }
        if ($_attributeValue): ?>
            <div class="product attibute <?php /* @escapeNotVerified */ echo $_className?>">
                <?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel;?></strong><?php echo $dots; endif; ?>
                <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; echo $fields[$i][2] ?></div>
            </div>
        <?php endif;
        $i++;
    }

?>

