<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    $_call = 'getTegi';
    $_code = 'tegi';

    $_attributeType = $block->getAtType();

    if ($_attributeType && $_attributeType == 'text') {
    	$_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
	} else {
	    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
	}

	$_call = 'getBrend';
	$_code = 'brend';

	$_attributeType2 = $block->getAtType();

	if ($_attributeType2 && $_attributeType2 == 'text') {
		$_attributeValue2 = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
	} else {
		$_attributeValue2 = $_helper->productAttribute($_product, $_product->$_call(), $_code);
	}

	if (strpos($_attributeValue, 'helvi-300a') !== false): ?>
		<div class="custom-block custom-block-1">
		    <div>
		        <em class="porto-icon-attention"></em>
		        <h3>Демонстрация!</h3>
		        <p>Бесплатная демонстрация аппарата в Москве и Московской области представителем компании-производителя.</p>
		    </div>
		</div>
	<?php elseif (($_attributeValue2 == 'Сварог')||($_attributeValue2 == 'ESAB')||($_attributeValue2 == 'EWM')): ?>
		<div class="custom-block custom-block-1">
		    <div>
		        <em class="porto-icon-attention"></em>
		        <h3>Демонстрация!</h3>
		        <p>Возможна демонстрация продукта в реальных условиях.</p>
		    </div>
		</div>
	<?php endif; ?>