<?php
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    if ($_product->getFinalPrice() != 0) {
		if ($_product->isAvailable()) { ?>
                <?php
                $_productHelper = $this->helper('Magento\Catalog\Helper\Product');
                $productPriceOCL = $_productHelper->getFinalPrice($_product);
                $productPriceOCL = str_replace('.0000','',$productPriceOCL);
                if ($productPriceOCL == '0') {
                    $productPriceOCL = "Звоните!";
                } else {
                    $productPriceOCL .= ' руб.';
                }
                ?>
                <a class="oneClickBuyButton"
                   name="test"
                   data-title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
                   data-img="<?php echo $_product->getImage(); ?>"
                   data-price="<?php echo $productPriceOCL; ?>"
                   data-url="<?php echo $_product->getProductUrl(); ?>">
                    Купить в 1 клик
                </a>

	    <?php
		}
	} else {
		//Товар с нулевой ценой
	}
?>