<?php 
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$_product = $block->getProduct();

    $_call = 'getTehnicheskie_harakteristiki';
    $_code = 'tehnicheskie_harakteristiki';

    $_attributeType = $block->getAtType();

    if ($_attributeType && $_attributeType == 'text') {
    	$_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
	} else {
	    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
	}

	if (($_attributeValue)&&($_attributeValue!='')&&($_attributeValue!=',')) {
		echo $_attributeValue;
	} else {
		echo 'Технические характеристики отсутствуют.';
	}
?>