<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>



<div data-block="minicart" class="minicart-wrapper col-md-2">
    <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>" data-bind="scope: 'minicart_content'">

        <div class="counter qty empty col-md-2" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
        </div>
        <div class="tiberis-cart-details col-md-10">

            <div class="tiberis-carttotalitems">
                <text>Товаров в корзине: </text><span class="tibvalue"><!-- ko text: getCartParam('summary_count') --><!-- /ko --> шт.</span>
            </div>

            <div class="tiberis-carttotalprice">
                <text>На сумму: </text><span data-bind="html: getCartParam('subtotal')"></span>
            </div>
        </div>
    </a>

    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>

