<?php
error_reporting(E_ALL);
ini_set('display_errors',1);
/*
$json_data = '{¶    "ExistInvoice": false,¶    "NumberOrder": "СК000030344",¶    "Consigner": {¶        "CompanyInfo": {¶            "Organization": "ООО \"СК Тиберис\"",¶            "ContactName": "Юрий Харитоненко",¶            "Phone": "+7 (495) 663-72-84 доб 112"¶        },¶        "Address": {¶            "MailIndex": "117587",¶            "Country": "Россия",¶            "TypeRegion": "г",¶            "Region": "Москва",¶            "TypeStreet": "ул",¶            "Street": "Варшавское шоссе",¶            "House": "125стр18",¶            "Apartament": null¶        }¶    },¶    "Consignee": {¶        "CompanyInfo": {¶            "ContactName": "Шишкин Артур Сергеевич",¶            "Phone": "+7(950) 006-21-18",¶            "Organization": "СТГ (ООО)"¶        },¶        "Address": {¶            "Country": "Россия",¶            "TypeRegion": "г",¶            "Region": "Санкт-Петербург",¶            "MailIndex": null,¶            "TypeSubRegion": null,¶            "SubRegion": null,¶            "TypeCity": null,¶            "City": null,¶            "TypePlace": null,¶            "Place": null,¶            "TypeStreet": "ул",¶            "Street": "Салова",¶            "House": "45к1",¶            "Apartament": null¶        }¶    },¶    "ContentType": "Parcel",¶    "DeliveryDate": "2016-05-20",¶    "DeliveryStartTime": "09:00:00",¶    "DeliveryEndTime": "18:00:00",¶    "ServiceType": 86,¶    "PriceType": "SEP",¶    "PriceService": 0,¶    "PriceServiceIsCashless": true,¶    "PriceServiceValuta": "RUB",¶    "PriceShop": 71753,¶    "PriceShopIsCashless": true,¶    "PriceShopValuta": "RUB",¶    "BoxAmount": 3,¶    "CargoPlaces": {¶        "id0": {¶            "Weight": "8",¶            "L": 0,¶            "H": 0,¶            "W": 0,¶            "Description": "Сварочный инвертор Fubag INTIG 200 DC Pulse",¶            "Quantity": "2",¶            "Price": "29294",¶            "PriceValuta": "RUB",¶            "IdNumNomenclature": "68439.1"¶        },¶        "id1": {¶            "Weight": "2",¶            "L": 0,¶            "H": 0,¶            "W": 0,¶            "Description": "Горелка FB TIG 26 5P 8m Up&Down",¶            "Quantity": "2",¶            "Price": "6582,5",¶            "PriceValuta": "RUB",¶            "IdNumNomenclature": "68311"¶        }¶    },¶    "Description": "Сварочный инвертор Fubag INTIG 200 DC Pulse (вес 8 кг.) - 2 шт.;Горелка FB TIG 26 5P 8m Up&Down (вес 2 кг.) - 2 шт.;",¶    "Comment": "Спб\nКлиент должен заполнить все поля УПД (всего 5 полей для юр. лиц), довер-ть д.б. заполнена по инструкции, вернуть один экземпляр УПД и довер-ть, если она есть."¶}';
//$json_data = '{"1": true, "asd": "asdd"}';
*/

$json_data = '{    "ExistInvoice": false,    "NumberOrder": "СК000030344",    "Consigner": {        "CompanyInfo": {            "Organization": "ООО \"СК Тиберис\"",            "ContactName": "Юрий Харитоненко",            "Phone": "+7 (495) 663-72-84 доб 112"        },        "Address": {            "MailIndex": "117587",            "Country": "Россия",            "TypeRegion": "г",            "Region": "Москва",            "TypeStreet": "ул",            "Street": "Варшавское шоссе",            "House": "125стр18",            "Apartament": null        }    },    "Consignee": {        "CompanyInfo": {            "ContactName": "Шишкин Артур Сергеевич",            "Phone": "+7(950) 006-21-18",            "Organization": "СТГ (ООО)"        },        "Address": {            "Country": "Россия",            "TypeRegion": "г",            "Region": "Санкт-Петербург",            "MailIndex": null,            "TypeSubRegion": null,            "SubRegion": null,            "TypeCity": null,            "City": null,            "TypePlace": null,            "Place": null,            "TypeStreet": "ул",            "Street": "Салова",            "House": "45к1",            "Apartament": null        }    },    "ContentType": "Parcel",    "DeliveryDate": "2016-05-20",    "DeliveryStartTime": "09:00:00",    "DeliveryEndTime": "18:00:00",    "ServiceType": 86,    "PriceType": "SEP",    "PriceService": 0,    "PriceServiceIsCashless": true,    "PriceServiceValuta": "RUB",    "PriceShop": 71753,    "PriceShopIsCashless": true,    "PriceShopValuta": "RUB",    "BoxAmount": 3,    "CargoPlaces": {        "id0": {            "Weight": "8",            "L": 0,            "H": 0,            "W": 0,            "Description": "Сварочный инвертор Fubag INTIG 200 DC Pulse",            "Quantity": "2",            "Price": "29294",            "PriceValuta": "RUB",            "IdNumNomenclature": "68439.1"        },        "id1": {            "Weight": "2",            "L": 0,            "H": 0,            "W": 0,            "Description": "Горелка FB TIG 26 5P 8m Up&Down",            "Quantity": "2",            "Price": "6582,5",            "PriceValuta": "RUB",            "IdNumNomenclature": "68311"        }    },    "Description": "Сварочный инвертор Fubag INTIG 200 DC Pulse (вес 8 кг.) - 2 шт.;Горелка FB TIG 26 5P 8m Up&Down (вес 2 кг.) - 2 шт.;",    "Comment": "Спб\nКлиент должен заполнить все поля УПД (всего 5 полей для юр. лиц), довер-ть д.б. заполнена по инструкции, вернуть один экземпляр УПД и довер-ть, если она есть."}';
$INVOICE_data = json_decode($json_data, true);

if (is_array($INVOICE_data)) {
	print_r($INVOICE_data);
} else {
	echo 'it is not array';
}

?>