<!--
<div class="column mainBottom">
    <?php
    $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
    ?>
    <?php if ($_category_desc == "main_column" && $_description = $block->getCurrentCategory()->getDescription()): ?>
        <div class="category-bottom-description">
            <?php
            $temp = $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description');
            $pieces = explode("razdelitel", $temp);
            //$one=substr($temp,0,283);
            echo '<p>'.$pieces[1];
            ?>
        </div>
    <?php endif; ?>
</div>
-->
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category=$objectManager->get('Magento\Framework\Registry')->registry('current_category');
    if($category){
        echo $category->getDescription();
    }
?>