<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

use Magento\Framework\App\Action\Action;

// Максимальная длина строки тайтла до ховера
$titleNoHoverMaxLength = 60;

// Массив формирования тайтлов
$vendorsArray = array();
$vendorsArray[0] = '3M';
$vendorsArray[1] = 'ABICOR BINZEL';
$vendorsArray[2] = 'AIKEN';
$vendorsArray[3] = 'AURORA';
$vendorsArray[4] = 'BLUEWELD';
$vendorsArray[5] = 'BRIMA';
$vendorsArray[6] = 'CASTOLIN';
$vendorsArray[7] = 'CHAMPION';
$vendorsArray[8] = 'ENDRESS';
$vendorsArray[9] = 'ERGOMAX';
$vendorsArray[10] = 'ESAB';
$vendorsArray[11] = 'EWM';
$vendorsArray[12] = 'FOXWELD';
$vendorsArray[13] = 'FUBAG';
$vendorsArray[14] = 'GASIQ';
$vendorsArray[15] = 'GCE';
$vendorsArray[16] = 'GCE KRASS';
$vendorsArray[17] = 'GENMAC';
$vendorsArray[18] = 'GYSMI';
$vendorsArray[19] = 'HELVI';
$vendorsArray[20] = 'HITACHI';
$vendorsArray[21] = 'HUTER';
$vendorsArray[22] = 'HYUNDAI';
$vendorsArray[23] = 'KEMPPI';
$vendorsArray[24] = 'LIDER';
$vendorsArray[25] = 'LINCOLN';
$vendorsArray[26] = 'LINCOLN ELECTRIC';
$vendorsArray[27] = 'METAFLUX';
$vendorsArray[28] = 'MOSA';
$vendorsArray[29] = 'NEON';
$vendorsArray[30] = 'REHM';
$vendorsArray[31] = 'SHINDAIWA';
$vendorsArray[32] = 'TECNA';
$vendorsArray[33] = 'TELWIN';
$vendorsArray[34] = 'TRAFIMET';
$vendorsArray[35] = 'TRANSLAS';
$vendorsArray[36] = 'TRITON';
$vendorsArray[37] = 'БАРС';
$vendorsArray[38] = 'ВИХРЬ';
$vendorsArray[39] = 'КРАСС';
$vendorsArray[40] = 'МЕЖГОСМЕТИЗ';
$vendorsArray[41] = 'ПАТОН';
$vendorsArray[42] = 'РЕСАНТА';
$vendorsArray[43] = 'СВАРОГ';
$vendorsArray[44] = 'СЕВЕР';
$vendorsArray[45] = 'СИБИРЬ';
$vendorsArray[46] = 'ТОРУС';
$vendorsArray[47] = 'ФЕБ';
$vendorsArray[48] = 'ФОРСАЖ';

$vendorsArrayReal = array();
$vendorsArrayReal[0] = '3m';
$vendorsArrayReal[1] = 'Abicor Binzel';
$vendorsArrayReal[2] = 'Aiken';
$vendorsArrayReal[3] = 'Aurora';
$vendorsArrayReal[4] = 'Blueweld';
$vendorsArrayReal[5] = 'Brima';
$vendorsArrayReal[6] = 'Castolin';
$vendorsArrayReal[7] = 'Champion';
$vendorsArrayReal[8] = 'Endress';
$vendorsArrayReal[9] = 'Ergomax';
$vendorsArrayReal[10] = 'Esab';
$vendorsArrayReal[11] = 'Ewm';
$vendorsArrayReal[12] = 'Foxweld';
$vendorsArrayReal[13] = 'Fubag';
$vendorsArrayReal[14] = 'Gasio';
$vendorsArrayReal[15] = 'Gce';
$vendorsArrayReal[16] = 'Gce Krass';
$vendorsArrayReal[17] = 'Genmac';
$vendorsArrayReal[18] = 'Gysmi';
$vendorsArrayReal[19] = 'Helvi';
$vendorsArrayReal[20] = 'Hitachi';
$vendorsArrayReal[21] = 'Huter';
$vendorsArrayReal[22] = 'Hyundai';
$vendorsArrayReal[23] = 'Kemppi';
$vendorsArrayReal[24] = 'Lider';
$vendorsArrayReal[25] = 'Lincoln';
$vendorsArrayReal[26] = 'Lincoln Electric';
$vendorsArrayReal[27] = 'Metaflux';
$vendorsArrayReal[28] = 'Mosa';
$vendorsArrayReal[29] = 'Neon';
$vendorsArrayReal[30] = 'Rehm';
$vendorsArrayReal[31] = 'Shindaiwa';
$vendorsArrayReal[32] = 'Tecna';
$vendorsArrayReal[33] = 'Telwin';
$vendorsArrayReal[34] = 'Trafimet';
$vendorsArrayReal[35] = 'Translas';
$vendorsArrayReal[36] = 'Triton';
$vendorsArrayReal[37] = 'Барс';
$vendorsArrayReal[38] = 'Вихрь';
$vendorsArrayReal[39] = 'Красс';
$vendorsArrayReal[40] = 'Межгосметиз';
$vendorsArrayReal[41] = 'Патон';
$vendorsArrayReal[42] = 'Ресанта';
$vendorsArrayReal[43] = 'Сварог';
$vendorsArrayReal[44] = 'Север';
$vendorsArrayReal[45] = 'Сибирь';
$vendorsArrayReal[46] = 'Торус';
$vendorsArrayReal[47] = 'Феб';
$vendorsArrayReal[48] = 'Форсаж';

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1;
                          $col = 0;
                    ?>
                    <?php foreach ($items as $_item): ?>
                        <?php
                            if ($col==0) {
                                echo '<li class="caurosel-col"><ul>';
                            }
                        ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info home-page">
                            <?php
                            $price = intval($_item->getSpecialPrice());
                            if ($price){ ?>
                                <?php
                                $price2 = intval($_item->getPrice());
                                $raznica = 100 - floor(($price/$price2)*100);
                                ?>
                                <span class="ptSale category-sticker" >
                                        <p><text>-<?php echo $raznica; ?>%</text></p>
                                    </span>
                            <?php } else {
                                $temp = $_helper->productAttribute($_item, $_item->getTegi(), 'Скидка: ');
                                if (strpos($temp, 'new') !== false) { ?>
                                    <span class="ptNew category-sticker" >
                                                <p><text>Новинка</text></p>
                                        </span>
                                <?php
                                } else {
                                    if (strpos($temp, 'stock') !== false) { ?>
                                        <span class="ptStock category-sticker" >
                                                <p><text>Акция</text></p>
                                            </span>
                                    <?php
                                    }
                                }
                                ?>

                            <?php } ?>
                            <div class="product-item-photo">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                            </div>
                            <div class="home-item-title">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                            </div>



                            <div class="product-item-details">

                                <div class="featured-price-wrapper">
                                    <?php
                                        $price = intval($_item->getSpecialPrice());
                                        $price2 = intval($_item->getPrice());
                                        if ($price) {
                                            $temp = number_format($price, 2, ',', ' ');
                                            $price = str_replace(',00','',$temp);
                                            $temp = number_format($price2, 2, ',', ' ');
                                            $price2 = str_replace(',00','',$temp);
                                            echo '<p class="homepageprice">'.$price.' руб.</p><p class="homepageprice2">'.$price2.' руб.</p>';
                                        } else {
                                            $temp = number_format($price2, 2, ',', ' ');
                                            $price2 = str_replace(',00','',$temp);
                                            echo '<p class="homepageprice2 def">'.$price2.' руб.</p>';
                                        }
                                    ?>
                                    <?php
                                        # echo $block->getProductPriceHtml($_item, $type);
                                    ?>
                                </div>

                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postParams = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
//"uenc":"ahr0cdovlzuxlji1nc4xmziumtm1lw,
                                                $temp = explode('enc":"',$postParams);
                                                $pieces = explode(',',$temp[1]);
                                            ?>


                                            <form data-role="tocart-form" action="<?php echo $block->getAddToCartUrl($_item); ?>" method="post">
                                                <input type="hidden" name="product" value="<?php echo $_item->getEntityId(); ?>">
                                                <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $pieces[0]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('В корзину')); ?>"
                                                        class="action tocart primary white-button">
                                                    <span><?php echo __('В корзину') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo __('В наличии') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo __('Нету в наличии') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php
                        $col++;
                        if ($col==2) {
                            $col = 0;
                            echo '</ul></li>';
                        }
                        ?>
                    <?php endforeach ?>
                    <?php
                    if ($col==1) {
                        echo '</ul></li>';
                    }
                    ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>